# Generated by Django 4.2.14 on 2024-07-29 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Meditation', 'meditation'), ('Affirmation', 'affirmation'), ('Breathing', 'breathing')], max_length=100)),
                ('video_id', models.CharField(max_length=100)),
                ('test_result', models.IntegerField()),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('answer_choice_1', models.CharField(max_length=255)),
                ('answer_choice_1_points', models.IntegerField(default=0)),
                ('answer_choice_2', models.CharField(max_length=255)),
                ('answer_choice_2_points', models.IntegerField(default=0)),
                ('answer_choice_3', models.CharField(max_length=255)),
                ('answer_choice_3_points', models.IntegerField(default=0)),
                ('answer_choice_4', models.CharField(max_length=255)),
                ('answer_choice_4_points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meditations.data')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
