version: "3"
services:

  # database:
  #   image: postgres:12.7-alpine
  #   volumes:
  #     - ./backup_data/db:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    # depends_on:
    #   - database
  
  reactapp:
    build: ./reactapp
    volumes:
      - ./reactapp:/app
    depends_on:
      - backend
    ports:
      - 80:80
  
  nginx_backend_server:
    build: ./nginx_backend_server
    ports:
      - 8000:8000
    depends_on:
      - backend
