version: "3"
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
  reactapp:
    build: ./reactapp
    volumes:
      - ./reactapp:/app
    depends_on:
      - backend
    ports:
      - 80:80
  
  nginx_backend_server:
    build: ./nginx_backend_server
    ports:
      - 8000:8000
    depends_on:
      - backend
